### PR TITLE
Added DateParser

### PR DESCRIPTION
**Pull request by edahlseng**
This pull request adds a DateParser for properly parsing Date objects from AppleScript output.

### CODE REVIEW

**Comment by edahlseng** [comment]
@TooTallNate bumping this PR. Do you need anything else from me before merging this?

**Comment by edahlseng** [comment]
@TooTallNate is anything else needed to merge this?

**Comment by edahlseng** [comment]
I'm cleaning up open PR's of mine, and so closing this. If anyone stumbles across this and needs it, I've published this change to [@eric.dahlseng/applescript on NPM](https://www.npmjs.com/package/@eric.dahlseng/applescript).

**Comment by TooTallNate** [comment]
Sorry about the delay, this LGTM.

**Comment by edahlseng** [comment]
Thanks @TooTallNate!

**Pull request merged**
